webapp/flaskr/library/models.py
from webapp.flaskr.db import db


class Author(db.Model):
    __tablename__ = 'Authors'

    author_id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), nullable=False)
    born = db.Column(db.Integer, nullable=False)
    died = db.Column(db.Integer, nullable=True)

    books = db.relationship("Book",
                            back_populates="authors",
                            secondary="BooksAuthors")


class Book(db.Model):
    __tablename__ = 'Books'

    book_id = db.Column(db.Integer, primary_key=True)
    lang_id = db.Column(db.ForeignKey("Languages.lang_id"), nullable=False)
    name = db.Column(db.String(128), nullable=False)
    released = db.Column(db.Integer, nullable=True)

    authors = db.relationship("Author",
                              back_populates="books",
                              secondary="BooksAuthors")
    genres = db.relationship("Genre",
                             back_populates="books",
                             secondary="BooksGenres")
    language = db.relationship("Language", back_populates="books")
    shelfbooks = db.relationship("ShelfBook", back_populates="book")


bookaut = db.Table(
    "BooksAuthors",
    db.Column("author_id",
              db.ForeignKey("Authors.author_id"),
              primary_key=True),
    db.Column("book_id", db.ForeignKey("Books.book_id"), primary_key=True),
)


class Genre(db.Model):
    __tablename__ = 'Genres'

    genre_id = db.Column(db.Integer, primary_key=True)
    genre = db.Column(db.String(64), nullable=False)

    books = db.relationship("Book",
                            back_populates="genres",
                            secondary="BooksGenres")


bookgen = db.Table(
    "BooksGenres",
    db.Column("genre_id", db.ForeignKey("Genres.genre_id"), primary_key=True),
    db.Column("book_id", db.ForeignKey("Books.book_id"), primary_key=True),
)


class Language(db.Model):
    __tablename__ = 'Languages'

    lang_id = db.Column(db.Integer, primary_key=True)
    lang = db.Column(db.String(64), nullable=False)

    books = db.relationship("Book", back_populates="language")


class ShelfBook(db.Model):
    __tablename__ = 'ShelfBooks'

    shelfbook_id = db.Column(db.Integer, primary_key=True)
    book_id = db.Column(db.ForeignKey("Books.book_id"), nullable=False)
    stocked_at = db.Column(db.Date, nullable=False)

    book = db.relationship("Book", back_populates="shelfbooks")
    borrowings = db.relationship("Borrowing", back_populates="shelfbook")


class User(db.Model):
    __tablename__ = 'Users'

    user_id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(32), nullable=False)
    last_name = db.Column(db.String(32), nullable=False)
    created_at = db.Column(db.DateTime, nullable=False)

    borrowings = db.relationship("Borrowing", back_populates="user")


class Borrowing(db.Model):
    __tablename__ = 'Borrowings'

    bor_id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.ForeignKey("Users.user_id"), nullable=False)
    shelfbook_id = db.Column(db.ForeignKey("ShelfBooks.book_id"),
                             nullable=False)
    borrowed_at = db.Column(db.Date, nullable=False)
    returned = db.Column(db.Integer, nullable=False)

    shelfbook = db.relationship("ShelfBook", back_populates="borrowings")
    user = db.relationship("User", back_populates="borrowings")

webapp/flaskr/library/__init__.py
from flask import Blueprint

bp = Blueprint('library',
               __name__,
               template_folder="templates",
               url_prefix='/library')

# Register views
from . import views

webapp/flaskr/library/views.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
)

from webapp.flaskr.library import bp
from webapp.flaskr.db import db

from .models import Book, Author, Genre, ShelfBook, Borrowing


@bp.route("/")
def index_view():

    def get_count(entity):
        sql = db.select(db.func.count()).select_from(entity)
        count = db.session.execute(sql).scalars()
        return list(count)[0]

    to_query = [Book, Author, Genre, ShelfBook, Borrowing]
    entities = {ent.__name__: get_count(ent) for ent in to_query}

    return render_template("library/index.html", entities=entities)


@bp.route("/books/")
def books_view():
    books = db.session.execute(db.select(Book).order_by(Book.name)).scalars()

    return render_template("library/books.html", books=books)


@bp.route("/books/<pk>")
def books_detail_view(pk):
    if not pk or not pk.isdigit():
        return redirect(url_for("library.books_view"))

    book = db.session.get(Book, pk)

    return render_template("library/books_detail.html", book=book)


@bp.route("/authors/")
def authors_view():
    authors = db.session.execute(db.select(Author).order_by(
        Author.name)).scalars()

    return render_template("library/authors.html", authors=authors)


@bp.route("/authors/<pk>")
def authors_detail_view(pk):
    if not pk or not pk.isdigit():
        return redirect(url_for("library.authors_view"))

    author = db.session.get(Author, pk)
    books = author.books

    return render_template("library/authors_detail.html",
                           author=author,
                           books=books)


@bp.route("/genres/")
def genres_view():
    genres = db.session.execute(db.select(Genre).order_by(
        Genre.genre)).scalars()

    return render_template("library/genres.html", genres=genres)


@bp.route("/genres/<pk>")
def genres_detail_view(pk):
    if not pk or not pk.isdigit():
        return redirect(url_for("library.genres_view"))

    genre = db.session.get(Genre, pk)
    books = genre.books

    return render_template("library/genres_detail.html",
                           genre=genre,
                           books=books)


@bp.route("/search")
def search_view():
    q = request.args.get("q")
    books = None
    if q:
        sql = db.select(Book).where(Book.name.ilike("%%%s%%" % q)).order_by(
            Book.name)
        books = db.session.execute(sql).scalars()

    return render_template("library/search.html", books=books)


@bp.route("/shelfbooks/")
def shelfbooks_view():
    sba = db.orm.aliased(ShelfBook)
    borrowed = db.select(Borrowing.shelfbook_id).where(Borrowing.returned == 0)
    sql = db.select(Book.book_id, Book.name, db.func.count(sba.book_id))\
            .select_from(Book)\
            .join(sba, db.and_(
                sba.shelfbook_id.not_in(borrowed),
                sba.book_id == Book.book_id
                ), isouter=True)\
            .group_by(Book.book_id)\
            .order_by(Book.name)

    shelfbooks = db.session.execute(sql)
    return render_template("library/shelfbooks.html", shelfbooks=shelfbooks)


@bp.route("/borrowings/")
def borrowings_view():
    sbb = db.orm.aliased(ShelfBook)
    borrowed = db.select(Borrowing.shelfbook_id).where(Borrowing.returned == 0)
    sql = db.select(Book.book_id, Book.name, db.func.count(sbb.book_id))\
            .select_from(Book)\
            .join(sbb, db.and_(
                sbb.shelfbook_id.in_(borrowed),
                sbb.book_id == Book.book_id
                ), isouter=True)\
            .group_by(Book.book_id)\
            .order_by(Book.name)

    borrowings = db.session.execute(sql)
    return render_template("library/borrowings.html", borrowings=borrowings)

webapp/flaskr/library/templates/library/authors.html
{% extends "base.html" %}

{% block content %}
<style>
    .table-container {
        display: flex;
        justify-content: center;
    }

    table tbody tr td:not(:last-child) {
        padding-right: 1em;
    }

    header {
        text-align: center;
    }
</style>

<header>
    <h1>Library - Authors</h1>
</header>

<div class="table-container">
<table>
    <thead>
        <tr>
            <th>Author</th>
            <th># Books</th>
        </tr>
    </thead>
    <tbody>
        {% for author in authors %}
        <tr>

            <td>
                <a href="{{ url_for('library.authors_detail_view', pk=author.author_id) }}">
                    {{ author.name }}
                </a>
            </td>
            <td>
            {% if author.books %}
                {{ author.books|length }}
            {% else %}
                -
            {% endif %}
            </td>

        </tr>
        {% endfor %}
    </tbody>
</table>
</div>

{% endblock %}

webapp/flaskr/library/templates/library/authors_detail.html
{% extends "base.html" %}

{% block content %}
<style>
    header {
        text-align: center;
    }

    .container {
        display: flex;
        justify-content: center;
    }

    .result {
        flex-basis: 50%;
    }
</style>

<header>
    <h1>Library - Author detail</h1>
    <h3>{{ author.name }}</h3>
</header>

<div class="container">
    <section class="result">
    {% if books %}
        <ul>
        {% for book in books %}
            <li>
                <a href="{{ url_for('library.books_detail_view', pk=book.book_id) }}">
                    {{ book.name }}
                </a>
            </li>
        {% endfor %}
        </ul>
    {% endif %}
    </section>
</div>

{% endblock %}

webapp/flaskr/library/templates/library/books.html
{% extends "base.html" %}

{% block content %}
<style>
    .table-container {
        display: flex;
        justify-content: center;
    }

    table tbody tr td:not(:last-child) {
        padding-right: 1em;
    }

    header {
        text-align: center;
    }
</style>

<header>
    <h1>Library - Books</h1>
</header>

<div class="table-container">
<table>
    <thead>
        <tr>
            <th>Book</th>
            <th>Authors</th>
            <th>Genres</th>
        </tr>
    </thead>
    <tbody>
        {% for book in books %}
        <tr>

            <td>
                <a href="{{ url_for('library.books_detail_view', pk=book.book_id) }}">
                    {{ book.name }}
                </a>
            </td>
            <td>
            {% if book.authors %}
                {% for author in book.authors %}
                    <a href="{{ url_for('library.authors_detail_view', pk=author.author_id) }}">
                        {{ author.name }}
                    </a>
                    {% if not loop.last %}, {% endif %}
                {% endfor %}
            {% else %}
                -
            {% endif %}
            </td>
            <td>
            {% if book.genres %}
                {% for genre in book.genres %}
                    <a href="{{ url_for('library.genres_detail_view', pk=genre.genre_id) }}">
                        {{ genre.genre }}
                    </a>
                    {% if not loop.last %}, {% endif %}
                {% endfor %}
            {% else %}
                -
            {% endif %}
            </td>

        </tr>
        {% endfor %}
    </tbody>
</table>
</div>

{% endblock %}

webapp/flaskr/library/templates/library/books_detail.html
{% extends "base.html" %}

{% block content %}
<style>
    header {
        text-align: center;
    }

    .container {
        display: flex;
        justify-content: center;
    }
</style>

<header>
    <h1>Library - Book detail</h1>
</header>

<div class="container">
    <section>
        <h3>{{ book.name }}</h3>

        <strong>Language</strong>: {{ book.language.lang }}<br>

        <strong>Authors</strong>:
        {% if book.authors %}
        <ul>
            {% for author in book.authors %}
                <li>
                    <a href="{{ url_for('library.authors_detail_view', pk=author.author_id) }}">
                        {{ author.name }}
                    </a>
                </li>
            {% endfor %}
        </ul>
        {% else %}
        -
        {% endif %}
        <br>

        <strong>Genres</strong>:
        {% if book.genres %}
        <ul>
            {% for genre in book.genres %}
                <li>
                    <a href="{{ url_for('library.genres_detail_view', pk=genre.genre_id) }}">
                        {{ genre.genre }}
                    </a>
                </li>
            {% endfor %}
        </ul>
        {% else %}
        -
        {% endif %}
        <br>
    </section>
</div>
{% endblock %}

webapp/flaskr/library/templates/library/borrowings.html
{% extends "base.html" %}

{% block content %}
<style>
    .table-container {
        display: flex;
        justify-content: center;
    }

    table tbody tr td:not(:last-child) {
        padding-right: 1em;
    }

    header {
        text-align: center;
    }
</style>

<header>
    <h1>Library - Borrowings</h1>
</header>

<div class="table-container">
<table>
    <thead>
        <tr>
            <th>Book</th>
            <th># Borrowed</th>
        </tr>
    </thead>
    <tbody>
        {% for (book_id, book_name, borrowed) in borrowings %}
        <tr>

            <td>
                <a href="{{ url_for('library.books_detail_view', pk=book_id) }}">
                    {{ book_name }}
                </a>
            </td>
            <td>
            {% if borrowed %}
                {{ borrowed }}
            {% else %}
                -
            {% endif %}
            </td>

        </tr>
        {% endfor %}
    </tbody>
</table>
</div>

{% endblock %}

webapp/flaskr/library/templates/library/genres.html
{% extends "base.html" %}

{% block content %}
<style>
    .table-container {
        display: flex;
        justify-content: center;
    }

    table tbody tr td:not(:last-child) {
        padding-right: 1em;
    }

    header {
        text-align: center;
    }
</style>

<header>
    <h1>Library - Genres</h1>
</header>

<div class="table-container">
<table>
    <thead>
        <tr>
            <th>Author</th>
            <th># Books</th>
        </tr>
    </thead>
    <tbody>
        {% for genre in genres %}
        <tr>

            <td>
                <a href="{{ url_for('library.genres_detail_view', pk=genre.genre_id) }}">
                    {{ genre.genre }}
                </a>
            </td>
            <td>
            {% if genre.books %}
                {{ genre.books|length }}
            {% else %}
                -
            {% endif %}
            </td>

        </tr>
        {% endfor %}
    </tbody>
</table>
</div>

{% endblock %}

webapp/flaskr/library/templates/library/genres_detail.html
{% extends "base.html" %}

{% block content %}
<style>
    header {
        text-align: center;
    }

    .container {
        display: flex;
        justify-content: center;
    }

    .result {
        flex-basis: 50%;
    }
</style>

<header>
    <h1>Library - Genre detail</h1>
    <h3>{{ genre.genre }}</h3>
</header>

<div class="container">
    <section class="result">
    {% if books %}
        <ul>
        {% for book in books %}
            <li>
                <a href="{{ url_for('library.books_detail_view', pk=book.book_id) }}">
                    {{ book.name }}
                </a>
            </li>
        {% endfor %}
        </ul>
    {% endif %}
    </section>
</div>

{% endblock %}

webapp/flaskr/library/templates/library/index.html
{% extends "base.html" %}

{% block content %}
<style>
    .table-container {
        display: flex;
        justify-content: center;
    }

    table tbody tr td:not(:last-child) {
        padding-right: 1em;
    }

    header {
        text-align: center;
    }
</style>

<header>
    <h1>Library index</h1>
</header>

<div class="table-container">
<table>
    <thead>
        <tr>
            <th>Entity</th>
            <th># entries</th>
        </tr>
    </thead>
    <tbody>
        {% for entity, count in entities.items() %}
        <tr>

            <td>
                {{ entity }}
            </td>
            <td>
                {{ count }}
            </td>

        </tr>
        {% endfor %}
    </tbody>
</table>
</div>

{% endblock %}

webapp/flaskr/library/templates/library/search.html
{% extends "base.html" %}

{% block content %}
<style>
    header {
        text-align: center;
    }
    form button, form input {
        border-radius: 0;
        font-family: Times Newer Roman;
    }

    .container {
        display: flex;
        justify-content: center;
    }

    .result {
        flex-basis: 50%;
    }
</style>

<header>
    <h1>Library - Search</h1>
    <div>
        <form action="{{ url_for('library.search_view') }}" method="GET">
            <label for="query">Query:</label>
            <input type="text" name="q" id="query">
            <button type="submit">Search</button>
        </form>
    </div>
</header>

<div class="container">
    <section class="result">
    {% if books %}
        <ul>
        {% for book in books %}
            <li>
                <a href="{{ url_for('library.books_detail_view', pk=book.book_id) }}">
                    {{ book.name }}
                </a>
            </li>
        {% endfor %}
        </ul>
    {% endif %}
    </section>
</div>


{% endblock %}

webapp/flaskr/library/templates/library/shelfbooks.html
{% extends "base.html" %}

{% block content %}
<style>
    .table-container {
        display: flex;
        justify-content: center;
    }

    table tbody tr td:not(:last-child) {
        padding-right: 1em;
    }

    header {
        text-align: center;
    }
</style>

<header>
    <h1>Library - ShelfBooks</h1>
</header>

<div class="table-container">
<table>
    <thead>
        <tr>
            <th>Book</th>
            <th># Available</th>
        </tr>
    </thead>
    <tbody>
        {% for (book_id, book_name, available) in shelfbooks %}
        <tr>

            <td>
                <a href="{{ url_for('library.books_detail_view', pk=book_id) }}">
                    {{ book_name }}
                </a>
            </td>
            <td>
            {% if available %}
                {{ available }}
            {% else %}
                -
            {% endif %}
            </td>

        </tr>
        {% endfor %}
    </tbody>
</table>
</div>

{% endblock %}